server:
  port: 8763

spring:
  zipkin:
    base-url: http://13.112.145.57:9411
  application:
    name: service-lucky

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"