server:
  port: 8761

spring:
  profiles:
    active: peer1

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8766/eureka/