eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign

feign:
  # feign启用hystrix，才能熔断、降级
  hystrix:
    enabled: true
  #开启压缩可以有效节约网络资源，但是会增加CPU压力，建议把最小压缩的文档大小适度调大一点
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  #      feign替换JDK默认的URLConnection为okhttp
  #      使用okhttp，能提高qps，因为okhttp有连接池和超时时间进行调优
  #  在配置文件中，禁用默认的http，启用okhttp
  httpclient:
    enabled: false
  okhttp:
    enabled: true

# hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000